### ISSUE TITLE
Suggestion: a possible note to add to the readme or FAQ

### ISSUE THREAD

**Issue by mh0w** [datasciencecampus/census21api#58]
I find I have to set `verify=False` when using the requests package in order to be able to use census21api. I'm pretty sure this is an issue on my end (issue with office network) rather than an issue with census21api, but it _might_ be an issue that others face too so it _might_ be worth mentioning this in the readme/FAQ.

I changed one line (77) in src\census21api\wrapper.py.

Was:
```py
        response = requests.get(url, verify=True)
```

Now:
```py
        response = requests.get(url, verify=False)
```

**Comment by MichaelaLawrenceONS** [comment]
@EdCussONS @daffidwilde What do you think we should do about this? I agree with Matthew that we should add something in the documentation but I am wondering if we should also make response = requests.get(url, verify=False) by default? You get a warning but I have the same result as Matthew if I try to use on an on-network laptop, it just doesn't work. I can confirm that I also tried the join-the-VPN-before-login trick and that doesn't solve the problem. It only works with verify=False.

**Comment by daffidwilde** [comment]
I have the exact same issue with my on-network machine (that’s why I did the live demo from my MacBook)… very annoying!

I don’t think we should set `verify=False` by default because that opens up a whole can of security worms. Instead, let’s expose `verify` as a parameter in `CensusAPI` and pass it to the `get()` method. The default should still be `True`, but we should add something to the README for sure.

**Comment by EdCussONS** [comment]
Something @MichaelaLawrenceONS and I discussed was a config file to check whether on an on-network connection and set verify by the result of that check (False if on-network, True if not), exposing the parameter is probably easier, but maybe not as foolproof

**Comment by daffidwilde** [comment]
I'm open to an alternative, so long as it doesn't become too weighty for the typical user. Let's find some time to chat it over 😸
